### ISSUE TITLE
DOM: text extends off bottom of page

### ISSUE THREAD

**Issue by dhowe** [dhowe/Memory#3]
![screen shot 2015-07-15 at 8 54 37 pm](https://cloud.githubusercontent.com/assets/737638/8699068/53e4f062-2b35-11e5-947d-9349f8b664fc.png)

**Comment by CyrusSUEN** [comment]
PR: https://github.com/dhowe/Memory/pull/4

**Comment by dhowe** [comment]
This is not an adequate fix -- the text can vary at different times by 5-6 lines at least. You need to make the container div expand to fit the current amount of text.

**Comment by CyrusSUEN** [comment]
> the current amount of text.

Is there any convenient way to get this info? Currently there are a bunch of spans of words in the DIV container.

**Comment by dhowe** [comment]
set the div to expand automatically -- https://stackoverflow.com/questions/10464716/div-expand-to-visually-fill-vertical-space

**Comment by CyrusSUEN** [comment]
> make the container div expand to fit the current amount of text.

PR: https://github.com/dhowe/Memory/pull/6
